# Nan_euclidean distance

In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
from sklearn.metrics.pairwise import nan_euclidean_distances
x=np.array([[3, np.nan, 2, 0],
              [5, 4, 1, 5],
              [6, 7, 7, 5],
              [6, 5, 4, np.nan]])
nan_euclidean_distances(x[[0]],x[[3]])

array([[5.09901951]])

In [4]:
nan_euclidean_distances(x[[0]],x[[1]])

array([[6.32455532]])

In [6]:
nan_euclidean_distances(x,x)

array([[0.        , 6.32455532, 8.86942313, 5.09901951],
       [6.32455532, 0.        , 6.78232998, 3.82970843],
       [8.86942313, 6.78232998, 0.        , 4.163332  ],
       [5.09901951, 3.82970843, 4.163332  , 0.        ]])

In [8]:
from sklearn.impute import KNNImputer
x=np.array([[3, np.nan, 2, 0],
              [5, 4, 1, 5],
              [6, 7, 7, 5],
              [6, 5, 4, np.nan]])

imputer=KNNImputer(n_neighbors=2,weights="uniform")
imputer.fit_transform(x)

array([[3. , 4.5, 2. , 0. ],
       [5. , 4. , 1. , 5. ],
       [6. , 7. , 7. , 5. ],
       [6. , 5. , 4. , 5. ]])

#  NearestNeighbors

In [9]:
from sklearn.neighbors import NearestNeighbors
datapoint =[[0,0,1.3]]

X=[[0,0,2],[1,0,0],[0,0,1]]

neigh=NearestNeighbors(n_neighbors=2,radius=0.4,metric="euclidean")
neigh.fit(X)
distances,indices=neigh.kneighbors(datapoint,n_neighbors=3)
print(distances)
print(indices)

[[0.3        0.7        1.64012195]]
[[2 0 1]]


# KNN

In [10]:
from sklearn.neighbors import KNeighborsClassifier
X_train = [[1,100],[4,400],[5,500],[6,600],[8,800],[9,900],[11,1100],[12,1200], [15,1500], [18,1800],[19,1900]]
y_train = [0,0,1,1,1,2,2,2,2,2,2]

X_test = [[2,200]]

knn=KNeighborsClassifier(n_neighbors=3,metric="euclidean",weights="uniform")
knn.fit(X_train,y_train)
print(knn.predict(X_test))

[0]


In [11]:
knn.kneighbors([[1,100]])

(array([[  0.        , 300.01499963, 400.0199995 ]]), array([[0, 1, 2]]))

In [12]:
print(knn.predict(X_test))

[0]
